/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Bolsa;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import Proyecto_Bolsa.Agregar_Bolsa;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luisk
 */
public class Agregar_Nacionalidad extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
 public String nacionalidad;
 public int id;
 public Consultas_BD base;
     
    public Agregar_Nacionalidad() {
        initComponents();
        this.setTitle("Agregar Nacionalidad");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.setSize(530,490);
        
        ImageIcon wallpaper=new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono=new ImageIcon(wallpaper.getImage().getScaledInstance(label_principal.getWidth(),
                label_principal.getHeight(),Image.SCALE_DEFAULT));
        label_principal.setIcon(icono);
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nacionalidad = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_id_nacion = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        label_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nacionalidad.setBackground(new java.awt.Color(102, 102, 255));
        txt_nacionalidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_nacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, 60));

        btn_ingresar.setBackground(new java.awt.Color(153, 153, 255));
        btn_ingresar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Nacionalidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txt_id_nacion.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_nacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_nacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_nacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id_nacionFocusLost(evt);
            }
        });
        getContentPane().add(txt_id_nacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 60));

        btn_modificar.setBackground(new java.awt.Color(153, 153, 255));
        btn_modificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, 40));

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 255));
        btn_eliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, 40));

        label_principal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_principal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
         nacionalidad = txt_nacionalidad.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
         id = Integer.parseInt(txt_id_nacion.getText());
            base = new Consultas_BD("nacionalidad",id,nacionalidad);
        if(!nacionalidad.equals("") && txt_id_nacion.getText()!=""){//Si hay informacion
            
            if(base.EncontrarRepeteciones("id_nac","nacion")==true){//Si se encontro la nacionalidad
                JOptionPane.showMessageDialog(null, "Ya hay una nacionalidad con ese id o nacionalidad ");
                this.Vaciar();
            }else{
              
                base.Insertar();
                
                
                JOptionPane.showMessageDialog(null,"Insercion Lograda");
               this.Vaciar();
               this.CampoVerde();
            }
        }else{//Si se dejo vacio
            JOptionPane.showMessageDialog(null,"No deben de estar vacio");
          this.CampoRojo();
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
          nacionalidad = txt_nacionalidad.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
         id = Integer.parseInt(txt_id_nacion.getText());
         
          if(!nacionalidad.equals("") && txt_id_nacion.getText()!=""){
              base = new Consultas_BD("nacionalidad",id,nacionalidad);
              base.Modificar("nacion","id_nac");
              this.Vaciar();
               
               
          }else{
            JOptionPane.showMessageDialog(null,"No deben de estar vacio");
            this.CampoRojo();
          }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
         nacionalidad = txt_nacionalidad.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
         id = Integer.parseInt(txt_id_nacion.getText());
         
          if(!nacionalidad.equals("") && txt_id_nacion.getText()!=""){
              base = new Consultas_BD("nacionalidad",id,nacionalidad);
              base.Eliminar("id_nac");
              this.Vaciar();
      
               txt_id_nacion.setBackground(Color.red);
               txt_nacionalidad.setBackground(Color.red);
               
          }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
            txt_nacionalidad.setBackground(Color.red);
            txt_id_nacion.setBackground(Color.red);
          }         
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_id_nacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id_nacionFocusLost
        try{
                id = Integer.parseInt(txt_id_nacion.getText());
             
             if(txt_id_nacion.getText().isEmpty()){
                txt_nacionalidad.setText("");
             }else{
                base = new Consultas_BD("nacionalidad",id,nacionalidad);
                txt_nacionalidad.setText(base.Buscar("id_nac"));
             }
        }catch(NumberFormatException ex){
            
        }    
    
    }//GEN-LAST:event_txt_id_nacionFocusLost
    
    public void Vaciar(){
        txt_id_nacion.setText("");
        txt_nacionalidad.setText("");
    }
    public void CampoVerde(){
        txt_id_nacion.setBackground(Color.green);
        txt_nacionalidad.setBackground(Color.green);
    }
    
    public void CampoRojo(){
        if(txt_id_nacion.getText()==""){
            txt_id_nacion.setBackground(Color.red);
        }else{
               txt_nacionalidad.setBackground(Color.red);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Nacionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Nacionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Nacionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Nacionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Nacionalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_principal;
    private javax.swing.JTextField txt_id_nacion;
    private javax.swing.JTextField txt_nacionalidad;
    // End of variables declaration//GEN-END:variables
}
