/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Bolsa;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.List;
import java.sql.Connection;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author luisk
 */
public class Agregar_Bolsa extends javax.swing.JFrame {
    public int buscar,buscar2,buscar3;
    public boolean vacio;
    Consultas_BD base,base1,base2;
     public int num_doc=0;
     public int id_bolsa;
     public  int buscar_doc1,buscar_doc2,buscar_doc3;
     Consultas_BD modificar = new Consultas_BD();
     //public int [] documentos_bolsa;
     
    public ArrayList<Integer> documents = new ArrayList();
    public ArrayList<Integer> update = new ArrayList();
   
    public Agregar_Bolsa() {
        initComponents();
        this.setTitle("Agregar_bolsa");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(1100,850);

          txt_id_doc1.setVisible(false);
          txt_documento1.setVisible(false);
          txt_id_doc2.setVisible(false);
          txt_documento2.setVisible(false);
          txt_back1.setVisible(false);
          txt_back2.setVisible(false);
          txt_back3.setVisible(false);
          
          
          btn_actu1.setVisible(false);
          btn_actu2.setVisible(false);
          btn_actu3.setVisible(false);
        
        ImageIcon wallpaper=new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono=new ImageIcon(wallpaper.getImage().getScaledInstance(label_principal.getWidth(),
                label_principal.getHeight(),Image.SCALE_DEFAULT));
        label_principal.setIcon(icono);
       
        this.AjustarBotones();
        this.repaint();
        
        
    }
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void AjustarBotones(){
        
      
         ImageIcon imagen2 = new ImageIcon("src/images_bolsa/update.jpg");
        Icon icono_img2 = new ImageIcon(imagen2.getImage().getScaledInstance(btn_update_bolsa.getWidth(), btn_update_bolsa.getHeight(), Image.SCALE_DEFAULT));
        btn_update_bolsa.setIcon(icono_img2);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_apellidoP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_num_empleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_sexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_apellidoM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nacionalidad = new javax.swing.JTextField();
        txt_fecha_nacimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        btn_agregar = new javax.swing.JButton();
        txt_perfil = new javax.swing.JTextField();
        txt_id_experiencia = new javax.swing.JTextField();
        txt_ingreso = new javax.swing.JTextField();
        txt_id_nacion = new javax.swing.JTextField();
        txt_id_perfil = new javax.swing.JTextField();
        txt_id_escuela = new javax.swing.JTextField();
        txt_curp = new javax.swing.JTextField();
        txt_experiencia = new javax.swing.JTextField();
        txt_escolaridad = new javax.swing.JTextField();
        cmb_doc = new javax.swing.JComboBox<>();
        txt_id_doc = new javax.swing.JTextField();
        txt_documento = new javax.swing.JTextField();
        txt_id_doc1 = new javax.swing.JTextField();
        txt_documento1 = new javax.swing.JTextField();
        txt_id_doc2 = new javax.swing.JTextField();
        txt_documento2 = new javax.swing.JTextField();
        btn_update_bolsa = new javax.swing.JButton();
        btn_actu1 = new javax.swing.JButton();
        txt_back1 = new javax.swing.JTextField();
        txt_back2 = new javax.swing.JTextField();
        txt_back3 = new javax.swing.JTextField();
        btn_actu2 = new javax.swing.JButton();
        btn_actu3 = new javax.swing.JButton();
        label_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1100, 950));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del Aspirante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        txt_apellidoP.setBackground(new java.awt.Color(102, 102, 255));
        txt_apellidoP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_apellidoP.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_apellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 150, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id_empleado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txt_num_empleado.setBackground(new java.awt.Color(102, 102, 255));
        txt_num_empleado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_num_empleado.setForeground(new java.awt.Color(255, 255, 255));
        txt_num_empleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_num_empleadoFocusLost(evt);
            }
        });
        txt_num_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_empleadoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_num_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        txt_direccion.setBackground(new java.awt.Color(102, 102, 255));
        txt_direccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 180, 40));

        txt_nombre.setBackground(new java.awt.Color(102, 102, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Materno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        cmb_sexo.setBackground(new java.awt.Color(102, 102, 255));
        cmb_sexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));
        getContentPane().add(cmb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sexo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txt_apellidoM.setBackground(new java.awt.Color(102, 102, 255));
        txt_apellidoM.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_apellidoM.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apellidoMKeyReleased(evt);
            }
        });
        getContentPane().add(txt_apellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 170, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Ingreso");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha Nacimiento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        txt_nacionalidad.setEditable(false);
        txt_nacionalidad.setBackground(new java.awt.Color(102, 102, 255));
        txt_nacionalidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_nacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        txt_nacionalidad.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_nacionalidadCaretUpdate(evt);
            }
        });
        getContentPane().add(txt_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 190, 40));

        txt_fecha_nacimiento.setBackground(new java.awt.Color(102, 102, 255));
        txt_fecha_nacimiento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_fecha_nacimiento.setForeground(new java.awt.Color(255, 255, 255));
        txt_fecha_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_nacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Escolaridad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        txt_telefono.setBackground(new java.awt.Color(102, 102, 255));
        txt_telefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 170, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nacionalidad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        cmb_estatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "B", "M" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 100, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Observaciones");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Perfil");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Experiencia");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Curp");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Documentos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 120, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Estatus");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        txt_observaciones.setBackground(new java.awt.Color(102, 102, 255));
        txt_observaciones.setColumns(20);
        txt_observaciones.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_observaciones.setForeground(new java.awt.Color(255, 255, 255));
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 300, 150));

        btn_agregar.setBackground(new java.awt.Color(102, 102, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 110, 90));

        txt_perfil.setEditable(false);
        txt_perfil.setBackground(new java.awt.Color(102, 102, 255));
        txt_perfil.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_perfil.setForeground(new java.awt.Color(255, 255, 255));
        txt_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_perfilActionPerformed(evt);
            }
        });
        getContentPane().add(txt_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 220, 50));

        txt_id_experiencia.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_experiencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_experiencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_experiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_experienciaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 70, 50));

        txt_ingreso.setBackground(new java.awt.Color(102, 102, 255));
        txt_ingreso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        txt_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ingresoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 40));

        txt_id_nacion.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_nacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_nacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_nacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_nacionActionPerformed(evt);
            }
        });
        txt_id_nacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_nacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_id_nacionKeyTyped(evt);
            }
        });
        getContentPane().add(txt_id_nacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 70, 40));

        txt_id_perfil.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_perfil.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_perfil.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_perfilKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 70, 50));

        txt_id_escuela.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_escuela.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_escuela.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_escuela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_escuelaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 50, 50));

        txt_curp.setBackground(new java.awt.Color(102, 102, 255));
        txt_curp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_curp.setForeground(new java.awt.Color(255, 255, 255));
        txt_curp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_curpActionPerformed(evt);
            }
        });
        getContentPane().add(txt_curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 230, 50));

        txt_experiencia.setEditable(false);
        txt_experiencia.setBackground(new java.awt.Color(102, 102, 255));
        txt_experiencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_experiencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_experiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_experienciaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 220, 50));

        txt_escolaridad.setEditable(false);
        txt_escolaridad.setBackground(new java.awt.Color(102, 102, 255));
        txt_escolaridad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_escolaridad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_escolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 210, 50));

        cmb_doc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmb_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " ", " " }));
        cmb_doc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_docItemStateChanged(evt);
            }
        });
        cmb_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_docActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 60, -1));

        txt_id_doc.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_doc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_doc.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_doc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_docKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 60, 40));

        txt_documento.setEditable(false);
        txt_documento.setBackground(new java.awt.Color(102, 102, 255));
        txt_documento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_documento.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 150, 40));

        txt_id_doc1.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_doc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_doc1.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_doc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_doc1KeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_doc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 60, 40));

        txt_documento1.setEditable(false);
        txt_documento1.setBackground(new java.awt.Color(102, 102, 255));
        txt_documento1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_documento1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_documento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 150, 40));

        txt_id_doc2.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_doc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_doc2.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_doc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_doc2KeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_doc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 60, 40));

        txt_documento2.setEditable(false);
        txt_documento2.setBackground(new java.awt.Color(102, 102, 255));
        txt_documento2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_documento2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_documento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 150, 40));

        btn_update_bolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_bolsaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update_bolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 120, 90));

        btn_actu1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actu1.setText("Actualizar_Doc");
        btn_actu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actu1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 150, -1));
        getContentPane().add(txt_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 50, 50));
        getContentPane().add(txt_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 50, 50));
        getContentPane().add(txt_back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 50, 50));

        btn_actu2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actu2.setText("Actualizar_Doc");
        btn_actu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actu2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 150, -1));

        btn_actu3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actu3.setText("Actualizar_Doc");
        btn_actu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actu3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 150, -1));
        getContentPane().add(label_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fecha_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_nacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_nacimientoActionPerformed
    
    private void txt_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_perfilActionPerformed

    private void txt_experienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_experienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_experienciaActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if(this.estaVacio()==true){
            JOptionPane.showMessageDialog(null,"Te falta llenar campos");
            this.Vaciar();
        }else{
            try{
        id_bolsa=Integer.parseInt(txt_num_empleado.getText());
        String nombre = txt_nombre.getText().trim().toLowerCase();
        String apellidoP = txt_apellidoP.getText().trim().toLowerCase();
        String apellidoM = txt_apellidoM.getText().trim().toLowerCase();
        String sex = this.Sexo();
        String nacimiento = txt_fecha_nacimiento.getText().trim();
        String direccion = txt_direccion.getText().trim().toLowerCase();
        String telefono = txt_telefono.getText().trim();
        String ingreso = txt_ingreso.getText().trim();
        int nacion = Integer.parseInt(txt_id_nacion.getText().trim());
        int perfil = Integer.parseInt(txt_id_perfil.getText().trim());
        int escuela = Integer.parseInt(txt_id_escuela.getText().trim());
        int exp = Integer.parseInt(txt_id_experiencia.getText().trim());
        String curp = txt_curp.getText().trim().toLowerCase();
        String estatus= this.Estatus();
        String observaciones = txt_observaciones.getText().trim().toLowerCase();
        
        if(estatus.equals("B") || estatus.equals("M")){
            JOptionPane.showMessageDialog(null,"No puedes ingresar uno de bolsa con ese estatus","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
             base = new Consultas_BD();
        base.Agregar_Bolsa(id_bolsa, nombre, apellidoP, apellidoM, sex, nacimiento, direccion, telefono, ingreso, nacion, perfil, escuela, exp, curp, estatus, observaciones);
        
        
        base.Agregar_Bolsa_Documento("bolsa_documentos",id_bolsa,this.num_documentos());
            
        this.Vaciar();
        }
        
        
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"No debe de estar vacio ningun campo","Error",JOptionPane.ERROR);
            }
        
        }  
    }//GEN-LAST:event_btn_agregarActionPerformed
    
    private void txt_curpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_curpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_curpActionPerformed

    private void txt_id_nacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_nacionKeyTyped
  
    }//GEN-LAST:event_txt_id_nacionKeyTyped
        
    private ArrayList<Integer> num_documentos(){
        switch(num_doc){
            case 1:
                documents.add(Integer.parseInt(txt_id_doc.getText()));
                break;
            case 2:
                 documents.add(Integer.parseInt(txt_id_doc.getText()));
                  documents.add(Integer.parseInt(txt_id_doc1.getText()));
                break;
                
            case 3:
                documents.add(Integer.parseInt(txt_id_doc.getText()));
                documents.add(Integer.parseInt(txt_id_doc1.getText()));
                documents.add(Integer.parseInt(txt_id_doc2.getText()));  
                break;
                   
        }
        
      
        return documents;
    }
    
    private ArrayList modificar(){
        switch(num_doc){
            case 1:
                documents.set(1, buscar);
                break;
                
            case 2:
                break;
                
            case 3:
                break;
        }
        return documents;
    }
    
    private void cmb_docItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_docItemStateChanged
                if(evt.getSource()== cmb_doc){
                   int documentos = cmb_doc.getSelectedIndex()+1;
                   if(documentos ==1){
                       txt_id_doc.setVisible(true);
                       txt_documento.setVisible(true);
                       txt_id_doc1.setVisible(false);
                       txt_documento1.setVisible(false);
                       txt_id_doc2.setVisible(false);
                       txt_documento2.setVisible(false);
                       
                   }else if(documentos ==2){
                         txt_id_doc.setVisible(true);
                       txt_documento.setVisible(true);
                       txt_id_doc1.setVisible(true);
                       txt_documento1.setVisible(true);
                       txt_id_doc2.setVisible(false);
                       txt_documento2.setVisible(false);
                  
                   }else if(documentos ==3){
                        txt_id_doc.setVisible(true);
                       txt_documento.setVisible(true);
                       txt_id_doc1.setVisible(true);
                       txt_documento1.setVisible(true);
                       txt_id_doc2.setVisible(true);
                       txt_documento2.setVisible(true);
                   
                   }
                }// TODO add your handling code here:
    }//GEN-LAST:event_cmb_docItemStateChanged

    private void Buscar_Documentos(String bolsa){
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("Select id_doc,descripcion from documentos inner join bolsa_documentos using(id_doc)"
                    + "where id_bolsa='"+bolsa+"'");
           
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                txt_id_doc.setText(String.valueOf(rs.getInt("id_doc")));

                txt_documento.setText(rs.getString("descripcion"));
          
                txt_back1.setText(String.valueOf(rs.getInt("id_doc")));
                
                btn_actu1.setVisible(true);
                
                num_doc=1;
                
               if(rs.next()){
            txt_id_doc1.setVisible(true);
            txt_documento1.setVisible(true);
            txt_id_doc1.setText(String.valueOf(rs.getInt("id_doc")));
      
            txt_documento1.setText(rs.getString("descripcion"));
            
         
            txt_back2.setText(String.valueOf(rs.getInt("id_doc")));
                
                btn_actu2.setVisible(true);
            
            num_doc=2;
            
            
               }if(rs.next()){   
                txt_id_doc2.setVisible(true);
                txt_documento2.setVisible(true);   
                txt_id_doc2.setText(String.valueOf(rs.getInt("id_doc")));
          
                txt_documento2.setText(rs.getString("descripcion"));
                
                txt_back3.setVisible(true);
                txt_back3.setText(String.valueOf(rs.getInt("id_doc")));
                
                btn_actu3.setVisible(true);
                
                num_doc=3;
               }
               
           
            }else{
                
            }
        }catch(SQLException ex){
            
        }
        //JOptionPane.showMessageDialog(null,"Numero de documentos: "+num_doc);
    }
    
    
    private void cmb_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_docActionPerformed

    private void btn_update_bolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_bolsaActionPerformed
            if(txt_num_empleado.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Debe de ingresar el numero de bolsa","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
              try{
                  Consultas_BD eliminar=new Consultas_BD("bolsa",Integer.parseInt(txt_num_empleado.getText()));
                  Consultas_BD muerto= new Consultas_BD();
                  Consultas_BD buscar_emp = new Consultas_BD();
             
                  
                   if( this.Estatus().equals("B") && buscar_emp.Encontrar_Empleados(Integer.parseInt(txt_num_empleado.getText()))==true){
                      JOptionPane.showMessageDialog(null, "No puede poner de baja uno en bolsa,\n si ya esta registrado como Empleado","Error",JOptionPane.ERROR_MESSAGE);
                      this.Vaciar();
                      
                  }else{
                       
                        Connection cn = Conexion.conectar();
                  PreparedStatement pst = cn.prepareStatement("Update bolsa set nombre=?,apellido_p=?,apellido_m=?,sexo=?,fecha_nacimiento=?,direccion=?,telefono=?,fecha_ingreso=?,id_nac=?,id_perfil=?,id_esc=?,id_exp=?,curp=?,estatus=?,observaciones=?"
                          + " where id_empleado='"+txt_num_empleado.getText()+"'");
                  pst.setString(1, txt_nombre.getText());
                  pst.setString(2, txt_apellidoP.getText());
                  pst.setString(3, txt_apellidoM.getText());
                  pst.setString(4, this.Sexo());
                  pst.setString(5, txt_fecha_nacimiento.getText());
                  pst.setString(6, txt_direccion.getText());
                  pst.setString(7, txt_telefono.getText());
                  pst.setString(8, txt_ingreso.getText());
                  pst.setString(9, txt_id_nacion.getText());
                  pst.setString(10, txt_id_perfil.getText());
                  pst.setString(11, txt_id_escuela.getText());
                  pst.setString(12, txt_id_experiencia.getText());
                  pst.setString(13, txt_curp.getText());
                  pst.setString(14, this.Estatus());
                  pst.setString(15, txt_observaciones.getText());
                  
  
                 
                  if(this.Estatus()=="M"){
                      JOptionPane.showMessageDialog(null,txt_nombre.getText()+" ha sido eliminado");
                      muerto.Insertar_Muerto_Bolsa(txt_nombre.getText(), txt_apellidoP.getText(), txt_apellidoM.getText(),Integer.parseInt(txt_num_empleado.getText()),txt_observaciones.getText());
                      eliminar.Eliminar("id_empleado");
                  }
                      

         
               
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null,"Actualizacion lograda");
                  this.Vaciar();
                  cn.close(); 
                   }
                  
              }catch(SQLException ex){
                  
              }
                    
            }
    }//GEN-LAST:event_btn_update_bolsaActionPerformed

    private void txt_nacionalidadCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_nacionalidadCaretUpdate
            try{
                buscar = Integer.parseInt(txt_id_nacion.getText().trim());
                base = new Consultas_BD("nacionalidad",buscar);
                if(txt_id_nacion.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                }else{
                    txt_nacionalidad.setText(base.Buscar("id_nac"));
                }
            }catch(NumberFormatException ex){
                //JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_id_nacion.setText("");
            }                    // TODO add your handling code here:
    }//GEN-LAST:event_txt_nacionalidadCaretUpdate

    private void txt_id_nacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_nacionActionPerformed

    }//GEN-LAST:event_txt_id_nacionActionPerformed

    private void txt_id_nacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_nacionKeyReleased
        try{
             try{
                buscar = Integer.parseInt(txt_id_nacion.getText().trim());
                base = new Consultas_BD("nacionalidad",buscar);
                if(txt_id_nacion.getText().isEmpty()){
                   txt_nacionalidad.setText("");
                }else{
                    txt_nacionalidad.setText(base.Buscar("id_nac"));
                }
            }catch(NumberFormatException ex){
               // JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_id_nacion.setText("");
            }  
        }catch(java.lang.IllegalStateException ex){  
            
        }
       
    }//GEN-LAST:event_txt_id_nacionKeyReleased

    private void txt_id_perfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_perfilKeyReleased
        try{
             try{
                buscar = Integer.parseInt(txt_id_perfil.getText().trim());
                base = new Consultas_BD("perfil",buscar);
                if(txt_id_perfil.getText().isEmpty()){
                   txt_perfil.setText("");
                }else{
                    txt_perfil.setText(base.Buscar("id_perfil"));
                }
            }catch(NumberFormatException ex){
               // JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_id_perfil.setText("");
            }
        }catch(java.lang.IllegalStateException ex){
        
        }
        
        
        
         // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_perfilKeyReleased

    private void txt_id_escuelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_escuelaKeyReleased
      try{
         try{
                buscar = Integer.parseInt(txt_id_escuela.getText().trim());
                base = new Consultas_BD("escolaridad",buscar);
                if(txt_id_escuela.getText().isEmpty()){
                    //JOptionPane.showMessageDialog(null,"Debe digitar un numero");
                    txt_escolaridad.setText("");
                }else{
                    txt_escolaridad.setText(base.Buscar("id_esc"));
                }
            }catch(NumberFormatException ex){
                //JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_id_escuela.setText("");
            }    
      }catch(java.lang.IllegalStateException ex){
          
      }       
    }//GEN-LAST:event_txt_id_escuelaKeyReleased

    private void txt_id_experienciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_experienciaKeyReleased
     try{
            try{
                buscar = Integer.parseInt(txt_id_experiencia.getText().trim());
                base = new Consultas_BD("experiencia",buscar);
                if(txt_id_experiencia.getText().isEmpty()){
                    //JOptionPane.showMessageDialog(null,"Debe digitar un numero");
                    txt_experiencia.setText("");
                }else{
                   txt_experiencia.setText(base.Buscar("id_exp"));
                }
            }catch(NumberFormatException ex){
                //JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_experiencia.setText("");
            }  
     }catch(java.lang.IllegalStateException ex){
         
     }
              
    }//GEN-LAST:event_txt_id_experienciaKeyReleased

    private void txt_id_docKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_docKeyReleased
       try{   
            
           if(txt_id_doc.getText().isEmpty()){
               txt_documento.setText("");
               num_doc=0;
           }else{
                 buscar_doc1 = Integer.parseInt(txt_id_doc.getText());
                 //JOptionPane.showMessageDialog(null, buscar);
                   base = new Consultas_BD("documentos",Integer.parseInt(txt_id_doc.getText()));
                   txt_documento.setText(base.Buscar("id_doc"));
                   num_doc=1;
                   
                   //documents.add(buscar);  
           }
               
            }catch(NumberFormatException ex){
                //JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_id_doc.setText("");
                //txt_id_doc1.setText("");
                //txt_id_doc2.setText("");
            }   
    }//GEN-LAST:event_txt_id_docKeyReleased

    private void txt_id_doc1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_doc1KeyReleased
       try{   
             
            if(txt_id_doc1.getText().isEmpty()){
               txt_documento1.setText("");
               num_doc=1;
               
               
            }else{    
                   buscar_doc2 = Integer.parseInt(txt_id_doc1.getText());
                   base1 = new Consultas_BD("documentos",Integer.parseInt(txt_id_doc1.getText()));
                   txt_documento1.setText(base1.Buscar("id_doc"));
                   num_doc=2;
                  
                   //documents.add(buscar2);
            }          
            }catch(NumberFormatException ex){
   
                
                txt_id_doc1.setText("");
               
            }   
    }//GEN-LAST:event_txt_id_doc1KeyReleased

    private void txt_id_doc2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_doc2KeyReleased
        try{   
            
            if(txt_id_doc2.getText().isEmpty()){
                txt_documento2.setText("");
                num_doc=2;
                
            }else{
                    buscar_doc3 = Integer.parseInt(txt_id_doc2.getText());
                   base2 = new Consultas_BD("documentos",Integer.parseInt(txt_id_doc2.getText()));
                    txt_documento2.setText(base2.Buscar("id_doc"));
                    num_doc=3;
                  
              
            }
                    
               
            }catch(NumberFormatException ex){
               // JOptionPane.showMessageDialog(null,"Debe de ser un numero");
               
                txt_id_doc2.setText("");
            }   
    }//GEN-LAST:event_txt_id_doc2KeyReleased

    private void txt_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ingresoActionPerformed

    private void txt_num_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_empleadoActionPerformed

    private void txt_apellidoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoMKeyReleased
         Consultas_BD buscar_muerto = new Consultas_BD();
         if(buscar_muerto.Encontrar_Muertos(txt_nombre.getText(), txt_apellidoP.getText(), txt_apellidoM.getText())==true){
             btn_agregar.setEnabled(false);
         }else{
               btn_agregar.setEnabled(true);
         }
         
    }//GEN-LAST:event_txt_apellidoMKeyReleased

    private void txt_num_empleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_num_empleadoFocusLost
try{
             if(txt_num_empleado.getText().isEmpty()){
                        txt_nombre.setText("");
                        txt_apellidoP.setText("");
                        txt_apellidoM.setText("");
                        txt_fecha_nacimiento.setText("");
                        txt_direccion.setText("");
                        txt_telefono.setText("");
                        txt_ingreso.setText("");
                        txt_id_nacion.setText("");
                        txt_nacionalidad.setText("");
                        txt_id_perfil.setText("");
                        txt_perfil.setText("");
                        txt_id_escuela.setText("");
                        txt_escolaridad.setText("");
                        txt_id_experiencia.setText("");
                        txt_experiencia.setText("");
                        txt_curp.setText("");
                        txt_id_doc.setText("");
                        txt_documento.setText("");
                        txt_id_doc1.setText("");
                        txt_id_doc1.setVisible(false);
                        txt_documento1.setText("");
                          txt_documento1.setVisible(false);
                        txt_id_doc2.setText("");
                        txt_id_doc2.setVisible(false);
                        txt_documento2.setText("");
                        txt_documento2.setVisible(false);
                        txt_observaciones.setText("");
                        cmb_estatus.setSelectedItem("V");
                        
            }else{
                 try{
                     id_bolsa=Integer.parseInt(txt_num_empleado.getText());
                     Consultas_BD bd_nac,bd_perfil,bd_esc,bd_exp;//bd_doc
                     
                     Connection cn= Conexion.conectar();
                     PreparedStatement pst = cn.prepareStatement("Select nombre,apellido_p,apellido_m,sexo,fecha_nacimiento,direccion,telefono,"
                             + "fecha_ingreso,id_nac,id_perfil,id_esc,id_exp,curp,estatus,observaciones from bolsa where id_empleado='"+id_bolsa+"'");
                   ResultSet rs = pst.executeQuery();
                     if(rs.next()){
                         txt_nombre.setText(rs.getString("nombre"));
                         txt_apellidoP.setText(rs.getString("apellido_p"));
                         txt_apellidoM.setText(rs.getString("apellido_m"));
                         cmb_sexo.setSelectedItem(rs.getString("sexo"));
                         txt_fecha_nacimiento.setText(rs.getString("fecha_nacimiento"));
                         txt_direccion.setText(rs.getString("direccion"));
                         txt_telefono.setText(rs.getString("telefono"));
                         txt_ingreso.setText(rs.getString("fecha_ingreso"));
                         txt_id_nacion.setText(String.valueOf(rs.getInt("id_nac")));
                         txt_id_perfil.setText(String.valueOf(rs.getInt("id_perfil")));
                         txt_id_escuela.setText(String.valueOf(rs.getInt("id_esc")));
                         txt_id_experiencia.setText(String.valueOf(rs.getInt("id_exp")));
                         txt_curp.setText(rs.getString("curp"));
                         cmb_estatus.setSelectedItem(rs.getString("estatus"));
                         txt_observaciones.setText(rs.getString("observaciones"));
                         
                         //
                         bd_perfil= new Consultas_BD("perfil",rs.getInt("id_perfil"));
                        bd_esc= new Consultas_BD("escolaridad",rs.getInt("id_esc"));
                         bd_exp= new Consultas_BD("experiencia",rs.getInt("id_exp"));
                         bd_nac= new Consultas_BD("nacionalidad",rs.getInt("id_nac"));
                         //
                          txt_perfil.setText(bd_perfil.Buscar("id_perfil"));
                          txt_escolaridad.setText(bd_esc.Buscar("id_esc"));
                          txt_experiencia.setText(bd_exp.Buscar("id_exp"));
                          txt_nacionalidad.setText(bd_nac.Buscar("id_nac"));
                          
                     }else{
                         //JOptionPane.showMessageDialog(null,"NO EXISTE EN BOLSA","Error",JOptionPane.ERROR_MESSAGE);
                     }
                     
                 }catch(SQLException ex){
                 }
                
            }
        }catch(java.lang.IllegalStateException ex){
            
        } 
         this.Buscar_Documentos(txt_num_empleado.getText());       
    }//GEN-LAST:event_txt_num_empleadoFocusLost

    private void btn_actu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actu1ActionPerformed
        if(txt_id_doc.getText().equals(txt_id_doc1.getText())|| txt_id_doc.getText().equals(txt_id_doc2.getText())){
            JOptionPane.showMessageDialog(null,"No se pueden repetir documentos","Error",JOptionPane.ERROR_MESSAGE);
            this.Vaciar();
        }else{
           Consultas_BD modificar_curso = new Consultas_BD();
        modificar.Modificar_Documentos(Integer.parseInt(txt_num_empleado.getText()),Integer.parseInt(txt_id_doc.getText()),Integer.parseInt(txt_back1.getText()));
        JOptionPane.showMessageDialog(null,"Actualizacion Hecha","Logrado",JOptionPane.INFORMATION_MESSAGE);
        this.Buscar_Documentos(txt_num_empleado.getText()); 
        }
        
        
    }//GEN-LAST:event_btn_actu1ActionPerformed

    private void btn_actu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actu2ActionPerformed
        if(txt_id_doc1.getText().equals(txt_id_doc.getText())|| txt_id_doc1.getText().equals(txt_id_doc2.getText())){
            JOptionPane.showMessageDialog(null,"No se pueden repetir documentos","Error",JOptionPane.ERROR_MESSAGE);
            this.Vaciar();
        } else{
          Consultas_BD modificar_curso = new Consultas_BD();
        modificar.Modificar_Documentos(Integer.parseInt(txt_num_empleado.getText()),Integer.parseInt(txt_id_doc1.getText()),Integer.parseInt(txt_back2.getText()));
        JOptionPane.showMessageDialog(null,"Logrado","Actualizacion Hecha",JOptionPane.INFORMATION_MESSAGE);
        this.Buscar_Documentos(txt_num_empleado.getText());  
        } 
    }//GEN-LAST:event_btn_actu2ActionPerformed

    private void btn_actu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actu3ActionPerformed
         
        if(txt_id_doc2.getText().equals(txt_id_doc.getText())|| txt_id_doc2.getText().equals(txt_id_doc1.getText())){
            JOptionPane.showMessageDialog(null,"No se pueden repetir documentos","Error",JOptionPane.ERROR_MESSAGE);
            this.Vaciar();
        }else{
              Consultas_BD modificar_curso = new Consultas_BD();
        modificar.Modificar_Documentos(Integer.parseInt(txt_num_empleado.getText()),Integer.parseInt(txt_id_doc2.getText()),Integer.parseInt(txt_back3.getText()));
        JOptionPane.showMessageDialog(null,"Logrado","Actualizacion Hecha",JOptionPane.INFORMATION_MESSAGE);
        this.Buscar_Documentos(txt_num_empleado.getText());
        }
    }//GEN-LAST:event_btn_actu3ActionPerformed

    private void MostrarDocumentos(){
        
    }
 private boolean estaVacio(){
     if(txt_nombre.getText().isEmpty()){
         txt_nombre.setBackground(Color.red);
         vacio = true;
     } if(txt_num_empleado.getText().isEmpty()){
         txt_num_empleado.setBackground(Color.red);
          vacio = true;
     }
      if(txt_apellidoP.getText().isEmpty()){
         txt_apellidoP.setBackground(Color.red);
          vacio = true;
     } if(txt_apellidoM.getText().isEmpty()){
         txt_apellidoM.setBackground(Color.red);
          vacio = true;
     } if(txt_fecha_nacimiento.getText().isEmpty()){
         txt_fecha_nacimiento.setBackground(Color.red);
          vacio = true;
     } if(txt_direccion.getText().isEmpty()){
         txt_direccion.setBackground(Color.red);
          vacio = true;
     } if(txt_telefono.getText().isEmpty()){
         txt_telefono.setBackground(Color.red);
          vacio = true;
     } if(txt_ingreso.getText().isEmpty()){
         txt_ingreso.setBackground(Color.red);
          vacio = true;
     } if(txt_curp.getText().isEmpty()){
         txt_curp.setBackground(Color.RED);
          vacio = true;
     } if(txt_observaciones.getText().isEmpty()){
         txt_observaciones.setBackground(Color.red);
          vacio = true;
     }if(txt_id_doc.getText().isEmpty()){
         txt_id_doc.setBackground(Color.red);
         vacio = true;
     }
     else{
         vacio = false;
     }
     return vacio;
 }
 private void Vaciar(){
     txt_num_empleado.setText("");
     txt_nombre.setText("");
     txt_apellidoP.setText("");
     txt_apellidoM.setText("");
     txt_fecha_nacimiento.setText("");
     txt_direccion.setText("");
     txt_telefono.setText("");
     txt_ingreso.setText("");
     txt_id_nacion.setText("");
     txt_nacionalidad.setText("");
     txt_id_perfil.setText("");
     txt_perfil.setText("");
     txt_id_escuela.setText("");
     txt_escolaridad.setText("");
     txt_id_experiencia.setText("");
     txt_experiencia.setText("");
     txt_curp.setText("");
     txt_observaciones.setText("");
     txt_id_doc.setText("");
      txt_documento.setText("");
      txt_id_doc1.setText("");
      txt_documento1.setText("");
       txt_id_doc2.setText("");
        txt_documento2.setText("");
        
        btn_actu1.setVisible(false);
        btn_actu2.setVisible(false);
        btn_actu3.setVisible(false);
        num_doc=0;
        documents.clear();
 }
 
   
   
   public String Sexo(){
       String sexo;
       int pos = cmb_sexo.getSelectedIndex()+1;
       if(pos ==1){
           sexo = "M";
       }else{
           sexo = "F";
       }
       return sexo;
   }
   
   public String Estatus(){
       String estatus;
       int pos = cmb_estatus.getSelectedIndex()+1;
       if(pos ==1){
           estatus = "V";
       }else if(pos ==2){
           estatus = "B";
       }else {
           estatus = "M";
       }
       return estatus;
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Bolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Bolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Bolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Bolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Bolsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actu1;
    private javax.swing.JButton btn_actu2;
    private javax.swing.JButton btn_actu3;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_update_bolsa;
    private javax.swing.JComboBox<String> cmb_doc;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_principal;
    private javax.swing.JTextField txt_apellidoM;
    private javax.swing.JTextField txt_apellidoP;
    private javax.swing.JTextField txt_back1;
    private javax.swing.JTextField txt_back2;
    private javax.swing.JTextField txt_back3;
    private javax.swing.JTextField txt_curp;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_documento;
    private javax.swing.JTextField txt_documento1;
    private javax.swing.JTextField txt_documento2;
    private javax.swing.JTextField txt_escolaridad;
    private javax.swing.JTextField txt_experiencia;
    private javax.swing.JTextField txt_fecha_nacimiento;
    private javax.swing.JTextField txt_id_doc;
    private javax.swing.JTextField txt_id_doc1;
    private javax.swing.JTextField txt_id_doc2;
    private javax.swing.JTextField txt_id_escuela;
    private javax.swing.JTextField txt_id_experiencia;
    private javax.swing.JTextField txt_id_nacion;
    private javax.swing.JTextField txt_id_perfil;
    private javax.swing.JTextField txt_ingreso;
    private javax.swing.JTextField txt_nacionalidad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_num_empleado;
    private javax.swing.JTextArea txt_observaciones;
    private javax.swing.JTextField txt_perfil;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
