/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Bolsa;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
/**
 *
 * @author luisk
 */
public class Agregar_Empleado extends javax.swing.JFrame {
    public int buscar,buscar2,buscar3;
    Consultas_BD base,base1,base2;
    public int id_bolsa,id_empleado;
    public boolean Vacio=false;
    public int num_curso;
    ArrayList<Integer> update = new ArrayList();
    public ArrayList<Integer> cursos = new ArrayList();
    Persona_Bolsa p;
    /**
     * Creates new form Agregar_Empleado
     */
    public Agregar_Empleado() {
        initComponents();
        this.setTitle("Agregar Empleado");
          this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(990, 740);
        
        
         ImageIcon wallpaper=new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono=new ImageIcon(wallpaper.getImage().getScaledInstance(label_principal.getWidth(),
                label_principal.getHeight(),Image.SCALE_DEFAULT));
        label_principal.setIcon(icono);
        
      this.txt_id_curso1.setVisible(false);
      this.txt_curso1.setVisible(false);
      this.txt_id_curso2.setVisible(false);
      this.txt_curso2.setVisible(false);
        
      txt_back1.setVisible(false);
          txt_back2.setVisible(false);
          txt_back3.setVisible(false);
          
          
          btn_actu1.setVisible(false);
          btn_actu2.setVisible(false);
          btn_actu3.setVisible(false);
      
        this.AjustarBotones();
        this.repaint();
        
    }

    private void AjustarBotones(){
        ImageIcon imagen1 = new ImageIcon("src/images/addUser.png");
        Icon icono_img1 = new ImageIcon(imagen1.getImage().getScaledInstance(btn_agregar.getWidth(), btn_agregar.getHeight(), Image.SCALE_DEFAULT));
        btn_agregar.setIcon(icono_img1);
        
   
        ImageIcon imagen3 = new ImageIcon("src/images_bolsa/update.jpg");
        Icon icono_img3 = new ImageIcon(imagen3.getImage().getScaledInstance(btn_update.getWidth(), btn_update.getHeight(), Image.SCALE_DEFAULT));
        btn_update.setIcon(icono_img3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id_puesto = new javax.swing.JTextField();
        txt_puesto = new javax.swing.JTextField();
        txt_id_bolsa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellidoP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_apellidoM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_sexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha_nacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_imss = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        No_Empleado = new javax.swing.JLabel();
        txt_ingreso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_id_dep = new javax.swing.JTextField();
        txt_dep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_id_hours = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_hours = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmb_curso = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txt_id_curso = new javax.swing.JTextField();
        txt_curso = new javax.swing.JTextField();
        txt_id_curso1 = new javax.swing.JTextField();
        txt_curso1 = new javax.swing.JTextField();
        txt_id_curso2 = new javax.swing.JTextField();
        txt_curso2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        txt_hours_final = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        cmb_he = new javax.swing.JComboBox<>();
        cmb_hf = new javax.swing.JComboBox<>();
        cmb_days = new javax.swing.JComboBox<>();
        txt_id_empleado = new javax.swing.JTextField();
        No_Empleado1 = new javax.swing.JLabel();
        txt_back1 = new javax.swing.JTextField();
        txt_back2 = new javax.swing.JTextField();
        txt_back3 = new javax.swing.JTextField();
        btn_actu1 = new javax.swing.JButton();
        btn_actu2 = new javax.swing.JButton();
        btn_actu3 = new javax.swing.JButton();
        label_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_puesto.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_puesto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_puesto.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_puestoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 50));

        txt_puesto.setEditable(false);
        txt_puesto.setBackground(new java.awt.Color(102, 102, 255));
        txt_puesto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_puesto.setForeground(new java.awt.Color(255, 255, 255));
        txt_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puestoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, 50));

        txt_id_bolsa.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_bolsa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_bolsa.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_bolsa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_bolsaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_bolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        txt_nombre.setEditable(false);
        txt_nombre.setBackground(new java.awt.Color(102, 102, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        txt_apellidoP.setEditable(false);
        txt_apellidoP.setBackground(new java.awt.Color(102, 102, 255));
        txt_apellidoP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_apellidoP.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_apellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, -1));

        txt_apellidoM.setEditable(false);
        txt_apellidoM.setBackground(new java.awt.Color(102, 102, 255));
        txt_apellidoM.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_apellidoM.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_apellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 140, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Materno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        txt_sexo.setEditable(false);
        txt_sexo.setBackground(new java.awt.Color(102, 102, 255));
        txt_sexo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_sexo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 80, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 140, -1));

        txt_fecha_nacimiento.setEditable(false);
        txt_fecha_nacimiento.setBackground(new java.awt.Color(102, 102, 255));
        txt_fecha_nacimiento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_fecha_nacimiento.setForeground(new java.awt.Color(255, 255, 255));
        txt_fecha_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_nacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 160, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id_bolsa:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txt_telefono.setEditable(false);
        txt_telefono.setBackground(new java.awt.Color(102, 102, 255));
        txt_telefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha_Ingreso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Departamento:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 130, -1));

        txt_imss.setBackground(new java.awt.Color(102, 102, 255));
        txt_imss.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_imss.setForeground(new java.awt.Color(255, 255, 255));
        txt_imss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_imssActionPerformed(evt);
            }
        });
        txt_imss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_imssKeyReleased(evt);
            }
        });
        getContentPane().add(txt_imss, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 100, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        No_Empleado.setBackground(new java.awt.Color(255, 255, 255));
        No_Empleado.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        No_Empleado.setForeground(new java.awt.Color(255, 255, 255));
        No_Empleado.setText("IMSS:");
        getContentPane().add(No_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        txt_ingreso.setBackground(new java.awt.Color(102, 102, 255));
        txt_ingreso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        txt_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ingresoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 120, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Id_horario:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 100, -1));

        txt_id_dep.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_dep.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_dep.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_depActionPerformed(evt);
            }
        });
        txt_id_dep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_depKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 70, 40));

        txt_dep.setEditable(false);
        txt_dep.setBackground(new java.awt.Color(102, 102, 255));
        txt_dep.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_dep.setForeground(new java.awt.Color(255, 255, 255));
        txt_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_depActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 120, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Id_Dep:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 70, -1));

        txt_id_hours.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_hours.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_hours.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_hours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_hoursKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 70, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("HS");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 70, -1));

        txt_hours.setEditable(false);
        txt_hours.setBackground(new java.awt.Color(102, 102, 255));
        txt_hours.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_hours.setForeground(new java.awt.Color(255, 255, 255));
        txt_hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoursActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 200, 50));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Puesto:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, -1));

        cmb_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmb_curso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_cursoItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 60, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Id_Puesto:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, -1));

        txt_id_curso.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_curso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_curso.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_curso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_cursoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 30));

        txt_curso.setEditable(false);
        txt_curso.setBackground(new java.awt.Color(102, 102, 255));
        txt_curso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_curso.setForeground(new java.awt.Color(255, 255, 255));
        txt_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cursoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 150, 30));

        txt_id_curso1.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_curso1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_curso1.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_curso1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_curso1KeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_curso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 50, 30));

        txt_curso1.setEditable(false);
        txt_curso1.setBackground(new java.awt.Color(102, 102, 255));
        txt_curso1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_curso1.setForeground(new java.awt.Color(255, 255, 255));
        txt_curso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_curso1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_curso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 150, 30));

        txt_id_curso2.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_curso2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_curso2.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_curso2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_curso2KeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_curso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 50, 30));

        txt_curso2.setEditable(false);
        txt_curso2.setBackground(new java.awt.Color(102, 102, 255));
        txt_curso2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_curso2.setForeground(new java.awt.Color(255, 255, 255));
        txt_curso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_curso2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_curso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 150, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Curso:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, -1));

        cmb_estatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "B", "M" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 50));

        txt_hours_final.setEditable(false);
        txt_hours_final.setBackground(new java.awt.Color(102, 102, 255));
        txt_hours_final.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_hours_final.setForeground(new java.awt.Color(255, 255, 255));
        txt_hours_final.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_hours_finalMouseClicked(evt);
            }
        });
        txt_hours_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hours_finalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hours_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 70, 50));

        txt_observaciones.setBackground(new java.awt.Color(102, 102, 255));
        txt_observaciones.setColumns(20);
        txt_observaciones.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_observaciones.setForeground(new java.awt.Color(255, 255, 255));
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 300, 150));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Observaciones:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 140, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("H.E");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 70, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("H.F");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 70, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Dias");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 70, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Estatus:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 70, -1));

        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 110, 70));

        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 110, 70));

        cmb_he.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmb_he.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", " ", " " }));
        getContentPane().add(cmb_he, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 50, -1));

        cmb_hf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmb_hf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        getContentPane().add(cmb_hf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 60, -1));

        cmb_days.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmb_days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(cmb_days, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 70, -1));

        txt_id_empleado.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_empleado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_empleado.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_empleadoActionPerformed(evt);
            }
        });
        txt_id_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_empleadoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 100, 40));

        No_Empleado1.setBackground(new java.awt.Color(255, 255, 255));
        No_Empleado1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        No_Empleado1.setForeground(new java.awt.Color(255, 255, 255));
        No_Empleado1.setText("No_Empleado");
        getContentPane().add(No_Empleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        getContentPane().add(txt_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 50, 30));
        getContentPane().add(txt_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 50, 30));
        getContentPane().add(txt_back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 50, 30));

        btn_actu1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actu1.setText("Act.Curso");
        btn_actu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actu1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        btn_actu2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actu2.setText("Act.Curso");
        btn_actu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actu2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        btn_actu3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actu3.setText("Act.Curso");
        btn_actu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actu3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));
        getContentPane().add(label_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puestoActionPerformed

    private void txt_fecha_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_nacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_nacimientoActionPerformed

    private void txt_imssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_imssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_imssActionPerformed

    private void txt_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ingresoActionPerformed

    private void txt_id_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_depActionPerformed

    private void txt_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_depActionPerformed

    private void txt_hoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoursActionPerformed

    private void txt_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cursoActionPerformed

    private void txt_curso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_curso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_curso1ActionPerformed

    private void txt_curso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_curso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_curso2ActionPerformed

    private void cmb_cursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_cursoItemStateChanged
    int  numero_curso = cmb_curso.getSelectedIndex()+1;
      if(numero_curso==1){
       txt_id_curso1.setVisible(false);
       txt_curso1.setVisible(false);
       txt_id_curso2.setVisible(false);
       txt_curso2.setVisible(false);
          
      }else if(numero_curso==2){   
       txt_id_curso1.setVisible(true);
       txt_curso1.setVisible(true);
       txt_id_curso2.setVisible(false);
       txt_curso2.setVisible(false);
      }else if(numero_curso==3){
       txt_id_curso1.setVisible(true);
       txt_curso1.setVisible(true);
       txt_id_curso2.setVisible(true);
       txt_curso2.setVisible(true);
      }
          
    }//GEN-LAST:event_cmb_cursoItemStateChanged
    private int Total_Semana(){
        int total,he,hf,dias;
        
        he = cmb_he.getSelectedIndex()+1;
        hf= cmb_hf.getSelectedIndex()+1;
        dias = cmb_days.getSelectedIndex()+1;
         
       if(he>=hf){
           JOptionPane.showMessageDialog(null,"Horario Entrada no puede ser mas que ");
       }
        
        total = dias*(hf-he);
        
        return total;
    }
    private ArrayList<Integer> num_cursos(){
        switch(num_curso){
            case 1:
                cursos.add(Integer.parseInt(txt_id_curso.getText()));
                break;
            case 2:
                cursos.add(Integer.parseInt(txt_id_curso.getText()));
                cursos.add(Integer.parseInt(txt_id_curso1.getText()));
                break;
                
            case 3:
                 cursos.add(Integer.parseInt(txt_id_curso.getText()));
                cursos.add(Integer.parseInt(txt_id_curso1.getText()));
                cursos.add(Integer.parseInt(txt_id_curso2.getText()));
                break;
        }
        return cursos;
    }
    
    
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
            if(this.EstaVacio()==false){
                JOptionPane.showMessageDialog(null,"Debe de llenar todos los campos","ERROR",JOptionPane.ERROR);
            }else{
                try{
                    id_empleado = Integer.parseInt(txt_id_empleado.getText());
                    id_bolsa = Integer.parseInt(txt_id_bolsa.getText());
                    int horario = Integer.parseInt(txt_id_hours.getText());
                    int puesto = Integer.parseInt(txt_id_puesto.getText());
                    int depto = Integer.parseInt(txt_id_dep.getText());
                    String status = this.Estatus();
                    String observaciones = txt_observaciones.getText().trim();
                    int imss = Integer.parseInt(txt_imss.getText());
                    String fecha = txt_ingreso.getText();
                    int total_horas = Integer.parseInt(txt_hours_final.getText());
                    
                    base = new Consultas_BD();
                    base.agregar_Empleado(id_empleado, id_bolsa, horario, puesto, depto, status, observaciones, imss, fecha,total_horas);
                    base.Agregar_Bolsa_Documento("curso_empleado", id_empleado, this.num_cursos());
                    this.Vaciar();
                }catch(Exception ex){
                }
            }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_hours_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hours_finalActionPerformed
              
    }//GEN-LAST:event_txt_hours_finalActionPerformed

    private void txt_id_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_empleadoActionPerformed

    private void txt_id_bolsaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_bolsaKeyReleased
          if(txt_id_bolsa.getText().isEmpty()){
            txt_nombre.setText("");
            txt_apellidoP.setText("");
            txt_apellidoM.setText("");
            txt_sexo.setText("");
            txt_fecha_nacimiento.setText("");
            txt_telefono.setText("");
         
         }else{
               try{
            buscar = Integer.parseInt(txt_id_bolsa.getText());
            Connection cn  = Conexion.conectar();
             PreparedStatement pst = cn.prepareStatement("Select nombre,apellido_p,apellido_m,sexo,fecha_nacimiento,telefono from bolsa where id_empleado='"+buscar+"'");
                   ResultSet rs= pst.executeQuery();
                   if(rs.next()){
                       txt_nombre.setText(rs.getString("nombre"));
                       txt_apellidoP.setText(rs.getString("apellido_p"));
                       txt_apellidoM.setText(rs.getString("apellido_m"));
                       txt_sexo.setText(rs.getString("sexo"));
                       txt_fecha_nacimiento.setText(rs.getString("fecha_nacimiento"));
                       txt_telefono.setText(rs.getString("telefono"));
                   }else{
                       
                   }
        

               
        }catch(SQLException ex){
            
             }
         }
         this.txt_id_empleadoKeyReleased(evt);
    }//GEN-LAST:event_txt_id_bolsaKeyReleased

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(txt_id_empleado.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Debe de ingresar el numero de bolsa","ERROR",JOptionPane.ERROR);
            }else{
              try{
                  Consultas_BD eliminar=new Consultas_BD("empleado",Integer.parseInt(txt_id_bolsa.getText()));
                  Consultas_BD muerto= new Consultas_BD();
                  Consultas_BD personas = new Consultas_BD();
                  Connection cn = Conexion.conectar();
                   PreparedStatement pst = cn.prepareStatement("Update empleado set id_horario=?,id_puesto=?,id_depto=?,estatus=?,observaciones=?,no_seguro=?,fecha_ingreso=?,total_horas=?"
                           + "where no_empleado='"+Integer.parseInt(txt_id_empleado.getText())+"'");
             
                  
                   pst.setString(1,txt_id_hours.getText());
                   pst.setString(2, txt_id_puesto.getText());
                   pst.setString(3, txt_id_dep.getText());
                   pst.setString(4, this.Estatus());
                   pst.setString(5, txt_observaciones.getText());
                   pst.setString(6, txt_imss.getText());
                   pst.setString(7, txt_ingreso.getText());
                   pst.setString(8, txt_hours_final.getText());
              
                   
                   
                  if(this.Estatus()=="M"){
                       JOptionPane.showMessageDialog(null,txt_nombre.getText()+" ha sido eliminado");
                      muerto.Insertar_Muerto_Bolsa(txt_nombre.getText(), txt_apellidoP.getText(), txt_apellidoM.getText(),Integer.parseInt(txt_id_bolsa.getText()),txt_observaciones.getText());
                      eliminar.Eliminar("id_bolsa");
                  }
                  if(this.Estatus()=="B"){
                      try{
                       personas.Buscar_Bolsa(id_bolsa, p);
                      eliminar.Eliminar("id_bolsa");
                      personas.Agregar_Bolsa(p.getNum_bolsa(), p.getNombre(), p.getApellido_P(), p.getApellido_m(), 
                     p.getSexo(), p.getFecha_nacimiento(), p.getDireccion(), p.getTelefono(), p.getFecha_ingreso(), p.getNac(), p.getPerfil(),
                     p.getEsc(), p.getExp(), p.getCurp(), p.getEstatus(), p.getObservaciones()); 
                      }catch(java.lang.NullPointerException ex2){
                          
                      }
                  
                  }
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null,"Actualizacion lograda");
                  this.Vaciar();
                  cn.close();
                  //pst.setString(1, );
              }catch(SQLException ex){
                  
              }
              
            }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_id_depKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_depKeyReleased
                  try{
            buscar = Integer.parseInt(txt_id_dep.getText());
            base = new Consultas_BD("departamento",buscar);
            if(txt_id_dep.getText()==""){
                JOptionPane.showMessageDialog(null,"Debe digitar un numero");
                txt_dep.setText("");
            }else{
                txt_dep.setText(base.Buscar("id_depto"));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Debe de ser un numero");
            txt_id_puesto.setText("");
        }   
    }//GEN-LAST:event_txt_id_depKeyReleased

    private void txt_id_puestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_puestoKeyReleased
            try{
            buscar = Integer.parseInt(txt_id_puesto.getText().trim());
            base = new Consultas_BD("puesto",buscar);
            if(txt_id_puesto.getText()==""){
                JOptionPane.showMessageDialog(null,"Debe digitar un numero");
                txt_puesto.setText("");
            }else{
                txt_puesto.setText(base.Buscar("id_puesto"));
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Debe de ser un numero");
            txt_id_puesto.setText("");
        }  
    }//GEN-LAST:event_txt_id_puestoKeyReleased

    private void txt_id_hoursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_hoursKeyReleased
          try{
            buscar = Integer.parseInt(txt_id_hours.getText().trim());
            base = new Consultas_BD("horario",buscar);
            if(txt_id_hours.getText()==""){
                JOptionPane.showMessageDialog(null,"Debe digitar un numero");
                txt_hours.setText("");
            }else{
                txt_hours.setText(base.Buscar("id_horario"));
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Debe de ser un numero");
            txt_id_puesto.setText("");
        }  
    }//GEN-LAST:event_txt_id_hoursKeyReleased

    private void txt_id_cursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_cursoKeyReleased
    try{   
              if(txt_id_curso.getText().isEmpty()){
               txt_curso.setText("");
               num_curso=0;
           }else{
                 buscar = Integer.parseInt(txt_id_curso.getText());
                 //JOptionPane.showMessageDialog(null, buscar);
                   base = new Consultas_BD("curso",Integer.parseInt(txt_id_curso.getText()));
                   txt_curso.setText(base.Buscar("id_curso"));
                   num_curso=1;
                   
                   //documents.add(buscar);  
           }
               
            }catch(NumberFormatException ex){
                //JOptionPane.showMessageDialog(null,"Debe de ser un numero");
                txt_id_curso.setText("");
                //txt_id_doc1.setText("");
                //txt_id_doc2.setText("");
            }           // TODO ad
    }//GEN-LAST:event_txt_id_cursoKeyReleased

    private void txt_id_curso1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_curso1KeyReleased
         try{   
             
            if(txt_id_curso1.getText().isEmpty()){
               txt_curso1.setText("");
               num_curso=1;
               
               
            }else{    
                   buscar2 = Integer.parseInt(txt_id_curso1.getText());
                   base1 = new Consultas_BD("curso",Integer.parseInt(txt_id_curso1.getText()));
                   txt_curso1.setText(base1.Buscar("id_curso"));
                   num_curso=2;
                  
                   //documents.add(buscar2);
            }          
            }catch(NumberFormatException ex){
   
                
                txt_id_curso1.setText("");
               
            }          // TODO ad
    }//GEN-LAST:event_txt_id_curso1KeyReleased

    private void txt_id_curso2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_curso2KeyReleased
         try{   
            
            if(txt_id_curso2.getText().isEmpty()){
                txt_curso2.setText("");
                num_curso=2;
                
            }else{
                    buscar3 = Integer.parseInt(txt_id_curso2.getText());
                   base2 = new Consultas_BD("curso",Integer.parseInt(txt_id_curso2.getText()));
                    txt_curso2.setText(base2.Buscar("id_curso"));
                    num_curso=3;
                  
              
            }
                    
               
            }catch(NumberFormatException ex){
               // JOptionPane.showMessageDialog(null,"Debe de ser un numero");
               
                txt_id_curso2.setText("");
            }          // TODO ad
    }//GEN-LAST:event_txt_id_curso2KeyReleased

    private void txt_id_empleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_empleadoKeyReleased
 try{
            if(txt_id_bolsa.getText().isEmpty()){
            this.Vaciar();
        }else{
           buscar = Integer.parseInt(txt_id_bolsa.getText());
           
           //base = new Consultas_BD("empleado",buscar);
             try{
                 Connection cn = Conexion.conectar();
                 PreparedStatement pst = cn.prepareStatement("Select no_empleado,id_horario,id_puesto,id_depto,estatus,observaciones,no_seguro,fecha_ingreso,total_horas "
                         + "from empleado where id_bolsa='"+buscar+"'");
                 ResultSet rs= pst.executeQuery();
                 if(rs.next()){
                     //txt_id_empleado.setText(rs.getString("no_empleado"));
                     txt_id_empleado.setText(rs.getString("no_empleado"));
                     txt_id_hours.setText(rs.getString("id_horario"));
                     txt_id_puesto.setText(rs.getString("id_puesto"));
                     txt_id_dep.setText(rs.getString("id_depto"));
                     cmb_estatus.setSelectedItem(rs.getString("estatus"));
                     txt_observaciones.setText(rs.getString("observaciones"));
                     txt_imss.setText(rs.getString("no_seguro"));
                     txt_ingreso.setText(rs.getString("fecha_ingreso"));
                     txt_hours_final.setText(rs.getString("total_horas"));
                    // txt_id_curso.setText(rs.getString("id_curso"));
                     
                     
                //this.txt_id_bolsaKeyReleased(evt); 
             this.txt_id_depKeyReleased(evt);
             this.txt_id_puestoKeyReleased(evt);
             this.txt_id_hoursKeyReleased(evt);
             this.txt_id_cursoKeyReleased(evt);
                    
             
             
             
                }
                 
             }catch(SQLException ex){
                 
             }
           
             
        } 
       }catch(NumberFormatException ex){
           
       }
       this.Buscar_Cursos(txt_id_empleado.getText());      
    }//GEN-LAST:event_txt_id_empleadoKeyReleased
private void Buscar_Cursos(String no_empleado){
     try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("Select id_curso,tipo_curso from curso inner join curso_empleado using(id_curso)"
                    + "where id_empleado='"+no_empleado+"'");
           
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                txt_id_curso.setText(String.valueOf(rs.getInt("id_curso")));
                txt_curso.setText(rs.getString("tipo_curso"));
                txt_back1.setText(String.valueOf(rs.getInt("id_curso")));
                
                btn_actu1.setVisible(true);
                num_curso=1;
                
                
               if(rs.next()){
            txt_id_curso1.setVisible(true);
            txt_curso1.setVisible(true);
            txt_id_curso1.setText(String.valueOf(rs.getInt("id_curso")));
            txt_curso1.setText(rs.getString("tipo_curso"));
            txt_back2.setText(String.valueOf(rs.getInt("id_curso")));
                
                btn_actu2.setVisible(true);
            num_curso=2;
            
            
               }if(rs.next()){   
                txt_id_curso2.setVisible(true);
                txt_curso2.setVisible(true);   
                txt_id_curso2.setText(String.valueOf(rs.getInt("id_cursp")));
                txt_curso2.setText(rs.getString("tipo_curso"));
                txt_back3.setText(String.valueOf(rs.getInt("id_curso")));
                
                btn_actu3.setVisible(true);
                num_curso=3;
                
                
               }
               
           
            }else{
                
            }
        }catch(SQLException ex){
            
        }
}
    
    
    private void txt_imssKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_imssKeyReleased
       try{
            buscar = Integer.parseInt(txt_imss.getText());
           base = new Consultas_BD("empleado",buscar);
           
           if(base.EncontrarRepeteciones_ID("no_seguro")==true){
               JOptionPane.showMessageDialog(null,"Ya existe ese numero de Seguro_Social");
               txt_imss.setText("");
           }
       }catch(java.lang.NumberFormatException ex){
           
       }
       
    }//GEN-LAST:event_txt_imssKeyReleased

    private void txt_hours_finalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_hours_finalMouseClicked
         int total = this.Total_Semana();
            if(total<=0){
                JOptionPane.showMessageDialog(null,"Esta mal su horario semanal","ERROR",JOptionPane.ERROR_MESSAGE);
                txt_hours_final.setText("");
            }else{
                txt_hours_final.setText(String.valueOf(total));
            }
    }//GEN-LAST:event_txt_hours_finalMouseClicked

    private void btn_actu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actu1ActionPerformed
if(txt_id_curso.getText().equals(txt_id_curso1.getText())|| txt_id_curso.getText().equals(txt_id_curso2.getText())){
            JOptionPane.showMessageDialog(null,"No se pueden repetir cursos","Error",JOptionPane.ERROR_MESSAGE);
            this.Vaciar();
        }else{
           Consultas_BD modificar_curso = new Consultas_BD();
        modificar_curso.Modificar_Cursos(Integer.parseInt(txt_id_empleado.getText()),Integer.parseInt(txt_id_curso.getText()),Integer.parseInt(txt_back1.getText()));
        JOptionPane.showMessageDialog(null,"Actualizacion Hecha","Logrado",JOptionPane.INFORMATION_MESSAGE);
        this.Buscar_Cursos(txt_id_empleado.getText()); 
        }        
    }//GEN-LAST:event_btn_actu1ActionPerformed

    private void btn_actu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actu2ActionPerformed
      if(txt_id_curso1.getText().equals(txt_id_curso.getText())|| txt_id_curso1.getText().equals(txt_id_curso2.getText())){
            JOptionPane.showMessageDialog(null,"No se pueden repetir cursos","Error",JOptionPane.ERROR_MESSAGE);
            this.Vaciar();
        }else{
           Consultas_BD modificar_curso = new Consultas_BD();
        modificar_curso.Modificar_Cursos(Integer.parseInt(txt_id_empleado.getText()),Integer.parseInt(txt_id_curso1.getText()),Integer.parseInt(txt_back2.getText()));
        JOptionPane.showMessageDialog(null,"Actualizacion Hecha","Logrado",JOptionPane.INFORMATION_MESSAGE);
        this.Buscar_Cursos(txt_id_empleado.getText()); 
        } 
    }//GEN-LAST:event_btn_actu2ActionPerformed

    private void btn_actu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actu3ActionPerformed
      if(txt_id_curso2.getText().equals(txt_id_curso.getText())|| txt_id_curso2.getText().equals(txt_id_curso1.getText())){
            JOptionPane.showMessageDialog(null,"No se pueden repetir cursos","Error",JOptionPane.ERROR_MESSAGE);
            this.Vaciar();
        }else{
           Consultas_BD modificar_curso = new Consultas_BD();
        modificar_curso.Modificar_Cursos(Integer.parseInt(txt_id_empleado.getText()),Integer.parseInt(txt_id_curso2.getText()),Integer.parseInt(txt_back3.getText()));
        JOptionPane.showMessageDialog(null,"Actualizacion Hecha","Logrado",JOptionPane.INFORMATION_MESSAGE);
        this.Buscar_Cursos(txt_id_empleado.getText()); 
        } 
    }//GEN-LAST:event_btn_actu3ActionPerformed
    private boolean EstaVacio(){
        if(txt_id_bolsa.getText().isEmpty()){
            txt_id_bolsa.setBackground(Color.red);
            Vacio = false;
        } if(txt_nombre.getText().isEmpty()){
            txt_nombre.setBackground(Color.red);
             Vacio = false;
        } if(txt_apellidoP.getText().isEmpty()){
            txt_apellidoP.setBackground(Color.red);
             Vacio = false;
        } if(txt_apellidoM.getText().isEmpty()){
            txt_apellidoM.setBackground(Color.red);
             Vacio = false;
        } if(txt_sexo.getText().isEmpty()){
            txt_sexo.setBackground(Color.red);
             Vacio = false;
        } if(txt_fecha_nacimiento.getText().isEmpty()){
            txt_fecha_nacimiento.setBackground(Color.red);
             Vacio = false;
        } if(txt_telefono.getText().isEmpty()){
            txt_telefono.setBackground(Color.red);
             Vacio = false;
        }
        
        else{
            Vacio = true;
        }
        
        return Vacio;
    }
    
    private String Estatus(){
        String estatus="";
        int pos = cmb_estatus.getSelectedIndex()+1;
        if(pos==1){
            estatus = "V";
        }if(pos==2){
            estatus = "B";
        }if(pos==3){
            estatus = "M";
        }
        return estatus;
    }
    
    private void Vaciar(){
        txt_id_bolsa.setText("");
        txt_nombre.setText("");
        txt_apellidoP.setText("");
        txt_apellidoM.setText("");
        txt_sexo.setText("");
        txt_fecha_nacimiento.setText("");
        txt_telefono.setText("");
        txt_id_empleado.setText("");
        txt_imss.setText("");
        txt_ingreso.setText("");
        txt_id_dep.setText("");
        txt_dep.setText("");
        txt_id_puesto.setText("");
        txt_puesto.setText("");
        txt_id_hours.setText("");
        txt_hours.setText("");
        txt_hours_final.setText("");
        txt_observaciones.setText("");
        txt_id_curso.setText("");
        txt_id_curso1.setText("");
        txt_id_curso2.setText("");
        txt_curso.setText("");
        txt_curso1.setText("");
        txt_curso2.setText("");
        cursos.clear();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel No_Empleado;
    private javax.swing.JLabel No_Empleado1;
    private javax.swing.JButton btn_actu1;
    private javax.swing.JButton btn_actu2;
    private javax.swing.JButton btn_actu3;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_curso;
    private javax.swing.JComboBox<String> cmb_days;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_he;
    private javax.swing.JComboBox<String> cmb_hf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_principal;
    private javax.swing.JTextField txt_apellidoM;
    private javax.swing.JTextField txt_apellidoP;
    private javax.swing.JTextField txt_back1;
    private javax.swing.JTextField txt_back2;
    private javax.swing.JTextField txt_back3;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_curso1;
    private javax.swing.JTextField txt_curso2;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_fecha_nacimiento;
    private javax.swing.JTextField txt_hours;
    private javax.swing.JTextField txt_hours_final;
    private javax.swing.JTextField txt_id_bolsa;
    private javax.swing.JTextField txt_id_curso;
    private javax.swing.JTextField txt_id_curso1;
    private javax.swing.JTextField txt_id_curso2;
    private javax.swing.JTextField txt_id_dep;
    private javax.swing.JTextField txt_id_empleado;
    private javax.swing.JTextField txt_id_hours;
    private javax.swing.JTextField txt_id_puesto;
    private javax.swing.JTextField txt_imss;
    private javax.swing.JTextField txt_ingreso;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextArea txt_observaciones;
    private javax.swing.JTextField txt_puesto;
    private javax.swing.JTextField txt_sexo;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
