/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Bolsa;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author luisk
 */
public class bolsa_trabajo extends javax.swing.JFrame {

    /**
     * Creates new form bolsa_trabajo
     */
    public bolsa_trabajo() {
        initComponents();
        this.setTitle("Bolsa de Trabajo");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.setSize(580,450);
        
         ImageIcon wallpaper=new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono=new ImageIcon(wallpaper.getImage().getScaledInstance(label_principal.getWidth(),
                label_principal.getHeight(),Image.SCALE_DEFAULT));
        label_principal.setIcon(icono);
        AjustarBotones();
        this.repaint();
    }
    
    private void AjustarBotones(){
         ImageIcon imagen1 = new ImageIcon("src/images_bolsa/agregar_bolsa.png");
        Icon icono_img1 = new ImageIcon(imagen1.getImage().getScaledInstance(btn_bolsa.getWidth(), btn_bolsa.getHeight(), Image.SCALE_DEFAULT));
        btn_bolsa.setIcon(icono_img1);
        
        ImageIcon imagen2 = new ImageIcon("src/images_bolsa/mexico.jpg");
        Icon icono_img2 = new ImageIcon(imagen2.getImage().getScaledInstance(btn_nacionalidad.getWidth(), btn_nacionalidad.getHeight(), Image.SCALE_DEFAULT));
        btn_nacionalidad.setIcon(icono_img2);
        
        ImageIcon imagen3 = new ImageIcon("src/images_bolsa/documentos.png");
        Icon icono_img3 = new ImageIcon(imagen3.getImage().getScaledInstance(btn_documentos.getWidth(), btn_documentos.getHeight(), Image.SCALE_DEFAULT));
        btn_documentos.setIcon(icono_img3);
        
         ImageIcon imagen4 = new ImageIcon("src/images_bolsa/escuela.png");
        Icon icono_img4 = new ImageIcon(imagen4.getImage().getScaledInstance(btn_escolaridad.getWidth(), btn_escolaridad.getHeight(), Image.SCALE_DEFAULT));
        btn_escolaridad.setIcon(icono_img4);
        
        ImageIcon imagen5 = new ImageIcon("src/images_bolsa/perfil.jpg");
        Icon icono_img5 = new ImageIcon(imagen5.getImage().getScaledInstance(btn_perfil.getWidth(), btn_perfil.getHeight(), Image.SCALE_DEFAULT));
        btn_perfil.setIcon(icono_img5);
        
        ImageIcon imagen6 = new ImageIcon("src/images_bolsa/experiencia.png");
        Icon icono_img6 = new ImageIcon(imagen6.getImage().getScaledInstance(btn_experiencia.getWidth(), btn_experiencia.getHeight(), Image.SCALE_DEFAULT));
        btn_experiencia.setIcon(icono_img6);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_experiencia = new javax.swing.JButton();
        btn_documentos = new javax.swing.JButton();
        btn_bolsa = new javax.swing.JButton();
        btn_nacionalidad = new javax.swing.JButton();
        btn_escolaridad = new javax.swing.JButton();
        btn_perfil = new javax.swing.JButton();
        jLabel_intro4 = new javax.swing.JLabel();
        jLabel_intro5 = new javax.swing.JLabel();
        jLabel_intro6 = new javax.swing.JLabel();
        jLabel_intro7 = new javax.swing.JLabel();
        jLabel_intro8 = new javax.swing.JLabel();
        jLabel_intro9 = new javax.swing.JLabel();
        jLabel_intro10 = new javax.swing.JLabel();
        label_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_experiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_experienciaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 120, 100));

        btn_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_documentosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_documentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 120, 100));

        btn_bolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bolsaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 100));

        btn_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nacionalidadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 120, 100));

        btn_escolaridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escolaridadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_escolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 100));

        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, 100));

        jLabel_intro4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_intro4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro4.setText("Agregar nacionalidad");
        getContentPane().add(jLabel_intro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 30));

        jLabel_intro5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_intro5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro5.setText("Eliga Opcion:");
        getContentPane().add(jLabel_intro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, 50));

        jLabel_intro6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_intro6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro6.setText("Agregar documentos");
        getContentPane().add(jLabel_intro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, 30));

        jLabel_intro7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_intro7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro7.setText("Agregar escolaridad");
        getContentPane().add(jLabel_intro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 30));

        jLabel_intro8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_intro8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro8.setText("Agregar Perfil");
        getContentPane().add(jLabel_intro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 120, 30));

        jLabel_intro9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_intro9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro9.setText("Agregar Experiencia");
        getContentPane().add(jLabel_intro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 130, 30));

        jLabel_intro10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_intro10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_intro10.setText("Agregar_bolsa");
        getContentPane().add(jLabel_intro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));
        getContentPane().add(label_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_experienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_experienciaActionPerformed
        new Experiencia().setVisible(true);
    }//GEN-LAST:event_btn_experienciaActionPerformed

    private void btn_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_documentosActionPerformed
        new documentos().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_documentosActionPerformed

    private void btn_bolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bolsaActionPerformed
        new Agregar_Bolsa().setVisible(true);                     // TODO add your handling code here:
    }//GEN-LAST:event_btn_bolsaActionPerformed

    private void btn_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nacionalidadActionPerformed
            new Agregar_Nacionalidad().setVisible(true);
    }//GEN-LAST:event_btn_nacionalidadActionPerformed

    private void btn_escolaridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escolaridadActionPerformed
        new Escolaridad().setVisible(true);                // TODO add your handling code here:
    }//GEN-LAST:event_btn_escolaridadActionPerformed

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed
        new Perfil().setVisible(true);
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       new Mantenimiento_bolsa().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bolsa_trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bolsa_trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bolsa_trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bolsa_trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bolsa_trabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bolsa;
    private javax.swing.JButton btn_documentos;
    private javax.swing.JButton btn_escolaridad;
    private javax.swing.JButton btn_experiencia;
    private javax.swing.JButton btn_nacionalidad;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JLabel jLabel_intro10;
    private javax.swing.JLabel jLabel_intro4;
    private javax.swing.JLabel jLabel_intro5;
    private javax.swing.JLabel jLabel_intro6;
    private javax.swing.JLabel jLabel_intro7;
    private javax.swing.JLabel jLabel_intro8;
    private javax.swing.JLabel jLabel_intro9;
    private javax.swing.JLabel label_principal;
    // End of variables declaration//GEN-END:variables
}
