/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Bolsa;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Conexion;
import java.sql.ResultSet;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author luisk
 */
public class documentos extends javax.swing.JFrame {

String documentos;
int id;
Consultas_BD base;
    /**
     * Creates new form documentos
     */
    public documentos() {
        initComponents();
         this.setTitle("Documentos");
        this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.setSize(580,250);
        
         ImageIcon wallpaper=new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono=new ImageIcon(wallpaper.getImage().getScaledInstance(label_principal.getWidth(),
                label_principal.getHeight(),Image.SCALE_DEFAULT));
        label_principal.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_doc = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_id_doc = new javax.swing.JTextField();
        label_principal = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Documentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        txt_doc.setBackground(new java.awt.Color(102, 102, 255));
        txt_doc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_doc.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 190, 50));

        btn_ingresar.setBackground(new java.awt.Color(153, 153, 255));
        btn_ingresar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 40));

        btn_modificar.setBackground(new java.awt.Color(153, 153, 255));
        btn_modificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 120, 40));

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 255));
        btn_eliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 100, 40));

        txt_id_doc.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_doc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_doc.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_doc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id_docFocusLost(evt);
            }
        });
        getContentPane().add(txt_id_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 60));

        label_principal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_principal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        id = Integer.parseInt(txt_id_doc.getText().trim());
        documentos = txt_doc.getText().trim().toLowerCase();
         base = new Consultas_BD("documentos",id,documentos);
        if(!documentos.equals("") && txt_id_doc.getText()!=""){
           if(base.EncontrarRepeteciones("id_doc","descripcion")==true){
                 JOptionPane.showMessageDialog(null, "Ya hay un documentos con ese id o documentos");
               this.Vaciar();
           }else{
               base.Insertar();
               this.Vaciar();
               this.CampoVerde();
           }
        }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
            this.CampoRojo();
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        documentos = txt_doc.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
        id = Integer.parseInt(txt_id_doc.getText());
        base = new Consultas_BD("documentos",id,documentos);
        if(!documentos.equals("") && txt_id_doc.getText()!=""){
           base.Modificar("descripcion","id_doc");
           this.Vaciar();
           this.CampoVerde();
        }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
            this.CampoRojo();
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        documentos = txt_doc.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
        id = Integer.parseInt(txt_id_doc.getText());
        base = new Consultas_BD("documentos",id,documentos);
        if(!documentos.equals("") && txt_id_doc.getText()!=""){
         base.Eliminar("id_doc");
         this.Vaciar();
         
        }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
          this.CampoRojo();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_id_docFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id_docFocusLost
         try{
                id = Integer.parseInt(txt_id_doc.getText());
             
             if(txt_id_doc.getText().isEmpty()){
                txt_doc.setText("");
             }else{
                base = new Consultas_BD("documentos",id,documentos);
                txt_doc.setText(base.Buscar("id_doc"));
             }
        }catch(NumberFormatException ex){
            
        }    
    }//GEN-LAST:event_txt_id_docFocusLost
   private void Vaciar(){
       txt_id_doc.setText("");
       txt_doc.setText("");
   }
   private void CampoVerde(){
       txt_id_doc.setBackground(Color.green);
       txt_doc.setBackground(Color.green);
   }
   private void CampoRojo(){
       txt_id_doc.setBackground(Color.red);
       txt_doc.setBackground(Color.red);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new documentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_principal;
    private javax.swing.JTextField txt_doc;
    private javax.swing.JTextField txt_id_doc;
    // End of variables declaration//GEN-END:variables
}
