/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Bolsa;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author luisk
 */
public class Puesto extends javax.swing.JFrame {
 int id;
 String puesto;
  public Consultas_BD base;
    /**
     * Creates new form Puesto
     */
    public Puesto() {
        initComponents();
         this.setTitle("Puesto");
        this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.setSize(600,240);
        
        ImageIcon wallpaper=new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono=new ImageIcon(wallpaper.getImage().getScaledInstance(label_principal.getWidth(),
                label_principal.getHeight(),Image.SCALE_DEFAULT));
        label_principal.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_id_puesto = new javax.swing.JTextField();
        txt_puesto = new javax.swing.JTextField();
        label_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Puesto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btn_ingresar.setBackground(new java.awt.Color(153, 153, 255));
        btn_ingresar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 40));

        btn_modificar.setBackground(new java.awt.Color(153, 153, 255));
        btn_modificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 40));

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 255));
        btn_eliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 100, 40));

        txt_id_puesto.setBackground(new java.awt.Color(102, 102, 255));
        txt_id_puesto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_id_puesto.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_puesto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id_puestoFocusLost(evt);
            }
        });
        getContentPane().add(txt_id_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 60));

        txt_puesto.setBackground(new java.awt.Color(102, 102, 255));
        txt_puesto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_puesto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, 60));

        label_principal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_principal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        id = Integer.parseInt(txt_id_puesto.getText().trim());
        puesto = txt_puesto.getText().trim().toLowerCase();
        base = new Consultas_BD("puesto",id,puesto);
        if(!puesto.equals("") && txt_id_puesto.getText()!=""){

            if(base.EncontrarRepeteciones("id_puesto","tipo_puesto")==true){
                 JOptionPane.showMessageDialog(null, "Ya hay un puesto con ese id o puesto");
                txt_puesto.setText("");
            }else{
                base.Insertar();
                JOptionPane.showMessageDialog(null,"Insercion Lograda");
                this.Vaciar();
                this.CampoVerde();

            }

        }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
            this.CampoRojo();
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        puesto= txt_puesto.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
        id = Integer.parseInt(txt_id_puesto.getText());
        base = new Consultas_BD("puesto",id,puesto);
        if(!puesto.equals("") && txt_id_puesto.getText()!=""){
            base.Modificar("tipo_puesto","id_puesto");
            this.Vaciar();
            this.CampoVerde();

        }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
            this.CampoRojo();
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        puesto = txt_puesto.getText().trim().toLowerCase();//Metodo para ingresar nacionalidad
        id = Integer.parseInt(txt_id_puesto.getText());
        base = new Consultas_BD("puesto",id,puesto);

        if(!puesto.equals("") && txt_id_puesto.getText()!=""){
            base.Eliminar("id_puesto");
            this.Vaciar();

        }else{
            JOptionPane.showMessageDialog(null,"No debe de estar vacio");
            this.CampoRojo();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_id_puestoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id_puestoFocusLost
         try{
                id = Integer.parseInt(txt_id_puesto.getText());
             
             if(txt_id_puesto.getText().isEmpty()){
                txt_puesto.setText("");
             }else{
                base = new Consultas_BD("puesto",id,puesto);
                txt_puesto.setText(base.Buscar("id_puesto"));
             }
        }catch(NumberFormatException ex){
            
        }    
    }//GEN-LAST:event_txt_id_puestoFocusLost
public void Vaciar(){
    txt_id_puesto.setText("");
    txt_puesto.setText("");
}
public void CampoVerde(){
    txt_id_puesto.setBackground(Color.green);
    txt_puesto.setBackground(Color.green);
}
public void CampoRojo(){
    if(txt_id_puesto.getText()!=""){
        txt_id_puesto.setBackground(Color.red);
    }else{
        txt_puesto.setBackground(Color.red);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_principal;
    private javax.swing.JTextField txt_id_puesto;
    private javax.swing.JTextField txt_puesto;
    // End of variables declaration//GEN-END:variables
}
